application: usermanagement-987
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /favicon.ico
  static_files: app/favicon.ico
  upload: app/favicon.ico

- url: /images
  static_dir: app/images

- url: /js
  static_dir: app/js

- url: /lib
  static_dir: app/lib

- url: /partials
  static_dir: app/partials

- url: /css
  static_dir: app/css

- url: /index.html
  static_files: app/index.html
  upload: app/index.html

- url: /
  static_files: app/index.html
  upload: app/index.html

- url: /.*
  script: userManagement.app
